build_from:
  aarch64: ghcr.io/hassio-addons/base:18.1.0
  amd64: ghcr.io/hassio-addons/base:18.1.0
  armv7: ghcr.io/hassio-addons/base:18.1.0
labels:
  org.opencontainers.image.title: "Voltronic: Home Assistant"
  org.opencontainers.image.description: "Voltronic for Home Assistant"
  org.opencontainers.image.source: "https://github.com/DmitryKadyshev/hassio-addons-voltronic"
  org.opencontainers.image.licenses: "MIT License"